webserver:
  port: "WEBSERVER__PORT"
  endpoint: "WEBSERVER__ENDPOINT"
  subscriptions: "WEBERVER__SUBCRIPTIONS"

prisma:
  endpoint: "PRISMA__ENDPOINT"
  secret: "PRISMA__SECRET"
  debug:
    __name: "PRISMA__DEBUG"
    __format: "json"

commander:
  enabled:
    __name: "COMMANDER__ENABLED"
    __format: "json"
  host: "COMMANDER__HOST"
  port: "COMMANDER__PORT"

email:
  enabled:
    __name: "EMAIL__ENABLED"
    __format: "json"
  preview:
    __name: "EMAIL__PREVIEW"
    __form: "json"
  reply: "EMAIL__REPLY"
  smtpUrl: "EMAIL__SMTP_URL"

mailchimp:
  enabled: 
    __name: "MAILCHIMP__ENABLED"
    __format: "json"
  apiKey: "MAILCHIMP__APIKEY"
  listId: "MAILCHIMP__LISTID"

registry:
  auth:
    __name: "REGISTRY__AUTH"
    __form: "json"

repository: "REPOSITORY"

helm:
  baseDomain: "HELM__BASE_DOMAIN"
  registryAuthSecret: "HELM__REGISTRY_AUTH_SECRET"
  acme:
    __name: "HELM__ACME"
    __format: "json"
  rbacEnabled:
    __name: "HELM__RBAC_ENABLED"
    __format: "json"
  releaseName: "HELM__RELEASE_NAME"
  releaseNamespace: "HELM__RELEASE_NAMESPACE"
  releaseVersion: "HELM__RELEASE_VERSION"
  singleNamespace:
    __name: "HELM__SINGLE_NAMESPACE"
    __format: "json"

auth:
  local:
    enabled:
      __name: "AUTH__LOCAL__ENABLED"
      __format: "json"
  auth0:
    enabled:
      __name: "AUTH__AUTH0__ENABLED"
      __format: "json"
    clientId: "AUTH__AUTH0__CLIENT_ID"
    baseDomain: "AUTH__AUTH0__BASE_DOMAIN"
    externalLogin: "AUTH__AUTH0__EXTERNAL_LOGIN"
  google:
    enabled:
      __name: "AUTH__GOOGLE__ENABLED"
      __format: "json"
    clientId: "AUTH__GOOGLE__CLIENT_ID"

jwtPassphrase: "JWT_PASSPHRASE"

authDuration: "AUTH_DURATION"

publicSignups:
  __name: "PUBLIC_SIGNUPS"
  __format: "json"

emailConfirmation:
  __name: "EMAIL_CONFIRMATION"
  __format: "json"
